//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCT.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Anotacion
    {
        public int idAnotacion { get; set; }
        [Display(Name = "Usuario")]
        public string nombreUsuario { get; set; }
        [Display(Name = "Cliente")]
        public string datosCliente { get; set; }
        [Display(Name = "Observación")]
        public string observacion { get; set; }
        [Display(Name = "IMEI")]
        public long imei { get; set; }
        [Display(Name = "Tipo Anotación")]
        public int idTipoAnotacion { get; set; }
    
        public virtual TipoAnotacion TipoAnotacion { get; set; }
    }
}
