//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCT.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Bitacora
    {
        [Display(Name = "ID")]
        public int idBitacora { get; set; }
        [Display(Name = "Usuario")]
        public string usuario { get; set; }
        [Display(Name = "Acción")]
        public string accion { get; set; }
        [Display(Name = "Fecha")]
        public System.DateTime fecha { get; set; }
    }
}
